name: CI

# Trigger on push to any branch and pull requests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python Application
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Run the Python script
    - name: Run hello.py
      run: |
        python3 hello.py

    # Step 4: Run the system info script
    - name: Run sysinfo.sh
      run: |
        chmod +x scripts/sysinfo.sh
        ./scripts/sysinfo.sh

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t devops-hello:ci .

    # Step 3: Run Docker container
    - name: Test Docker container
      run: |
        docker run --rm devops-hello:ci


